server:
  port: 8083

spring:
  application:
    name: InventoryService

  datasource:
    url: jdbc:postgresql://localhost:5433/inventory
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventoryGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: by.example.bookstore_api.kafka.OrderEventDto:by.example.inventoryservice.model.dto.OrderEventDto
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: info
    by.example.bookstore_api: debug
  file:
    path: logs/app.log

